import Foundation

/// One copied text. Equal texts collapse into one entry that moves to the top.
public struct ClipboardEntry: Codable, Equatable, Sendable {
    public let text: String
    public let capturedAt: Date

    public init(text: String, capturedAt: Date) {
        self.text = text
        self.capturedAt = capturedAt
    }

    /// First non-blank line with runs of whitespace collapsed: the list row.
    public var title: String {
        let line = text.split(whereSeparator: \.isNewline).first { !$0.trimmingCharacters(in: .whitespaces).isEmpty } ?? ""
        return line.split(whereSeparator: \.isWhitespace).joined(separator: " ")
    }

    public var lineCount: Int { text.split(whereSeparator: \.isNewline).count }
}

/// Pure clipboard history: newest first, capped, no I/O. The monitor feeds
/// it, the store persists it, the panel reads it.
public struct ClipboardHistory: Codable, Equatable, Sendable {
    public static let limit = 200
    /// Pasteboard types that mark a write as secret or ephemeral. Password
    /// managers set the first two; nothing carrying them is ever recorded.
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]
    public static let empty = ClipboardHistory(entries: [])

    public var entries: [ClipboardEntry]

    public init(entries: [ClipboardEntry]) {
        self.entries = entries
    }

    public static func records(types: [String]) -> Bool {
        !types.contains(where: ignoredTypes.contains)
    }

    public func adding(_ text: String, at date: Date) -> ClipboardHistory {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return self }
        var next = entries.filter { $0.text != text }
        next.insert(ClipboardEntry(text: text, capturedAt: date), at: 0)
        return ClipboardHistory(entries: Array(next.prefix(Self.limit)))
    }

    public func filtered(_ query: String) -> [ClipboardEntry] {
        let needle = query.trimmingCharacters(in: .whitespaces)
        guard !needle.isEmpty else { return entries }
        return entries.filter { $0.text.localizedCaseInsensitiveContains(needle) }
    }
}
